export const LORDICON_TOKEN =
	'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6MTY3LCJzZWNyZXQiOiI4YkNCR21CNVhEQklDS0dKUFRMTTJJcFhyRUlLR09xZiIsImlhdCI6MTc2NTg2NjM4Nn0.vdQ_UeCQpJznjViPtt9H4DyKNETqhqEEXXGf8RjzDgk';

export const LORDICON_ICONS = {
	home: 'https://cdn.lordicon.com/wmwqvixz.json',
	settings: 'https://cdn.lordicon.com/lecprnjb.json',
	user: 'https://cdn.lordicon.com/hrjifpbq.json',
	search: 'https://cdn.lordicon.com/kkvxgpti.json',
	mail: 'https://cdn.lordicon.com/diihvcfp.json',
	heart: 'https://cdn.lordicon.com/ohfmmfhn.json',
	star: 'https://cdn.lordicon.com/surjmvno.json',
	check: 'https://cdn.lordicon.com/yqzmiobz.json',
	close: 'https://cdn.lordicon.com/nqtddedc.json',
	menu: 'https://cdn.lordicon.com/eouimtlu.json',
	arrow: 'https://cdn.lordicon.com/whtfgdfm.json',
	download: 'https://cdn.lordicon.com/ternnbni.json',
	upload: 'https://cdn.lordicon.com/rehjpyyh.json',
	edit: 'https://cdn.lordicon.com/wuvorxbv.json',
	trash: 'https://cdn.lordicon.com/skkahier.json',
	share: 'https://cdn.lordicon.com/wxnxiano.json',
	notification: 'https://cdn.lordicon.com/psnhyobz.json',
	lock: 'https://cdn.lordicon.com/aucyvhjc.json',
	unlock: 'https://cdn.lordicon.com/wjyqkiew.json',
	play: 'https://cdn.lordicon.com/becebamh.json',
	pause: 'https://cdn.lordicon.com/aklfruoc.json',
	refresh: 'https://cdn.lordicon.com/qhkvfxpn.json',
	send: 'https://cdn.lordicon.com/aycieyht.json',
	copy: 'https://cdn.lordicon.com/depeqmsz.json',
	info: 'https://cdn.lordicon.com/yxczfiyc.json',
	warning: 'https://cdn.lordicon.com/rslnizbt.json',
	error: 'https://cdn.lordicon.com/tdrtiskw.json',
	success: 'https://cdn.lordicon.com/oqdmuxru.json',
	loading: 'https://cdn.lordicon.com/xjovhxra.json',
	calendar: 'https://cdn.lordicon.com/abfverha.json',
	clock: 'https://cdn.lordicon.com/kbtmbyzy.json',
	location: 'https://cdn.lordicon.com/surcxhka.json',
	phone: 'https://cdn.lordicon.com/srsgifqc.json',
	camera: 'https://cdn.lordicon.com/vixtkkbk.json',
	image: 'https://cdn.lordicon.com/eflfmgmj.json',
	file: 'https://cdn.lordicon.com/rbbnmpcf.json',
	folder: 'https://cdn.lordicon.com/cnpvyndp.json',
	link: 'https://cdn.lordicon.com/wzrwaorf.json',
	bookmark: 'https://cdn.lordicon.com/gigfpovs.json',
	cart: 'https://cdn.lordicon.com/mfmkufkr.json',
	chat: 'https://cdn.lordicon.com/zpxybbhl.json',
	globe: 'https://cdn.lordicon.com/iltqorsz.json',
	sun: 'https://cdn.lordicon.com/dycatggu.json',
	moon: 'https://cdn.lordicon.com/evyuuwna.json',
	rocket: 'https://cdn.lordicon.com/akqsdstj.json',
	code: 'https://cdn.lordicon.com/mrdiiocb.json',
	github: 'https://cdn.lordicon.com/ynwbvguu.json',
	linkedin: '/icons/work.json',
	twitter: 'https://cdn.lordicon.com/zfmcashd.json',
	// Launch/Share icon for external links
	launch: '/icons/launch.json',
	work: '/icons/work.json'
} as const;

export type LordIconName = keyof typeof LORDICON_ICONS;
